import { InquiryItem } from '../types';

export const SAMPLE_INQUIRIES: InquiryItem[] = [
  {
    id: 'inq_sample_001',
    inquiryNumber: 'INQ-2026-001',
    date: '2026-08-24',
    customerName: 'AeroTech Gadgets Inc.',
    customerContact: '+1 (555) 234-8901 / aero@gmail.com',
    country: 'United States',
    product: 'Magnetic Wireless Charging Power Bank 10,000mAh (Custom Logo)',
    productUrl1688: 'https://detail.1688.com/offer/74218903.html',
    supplierName: 'Shenzhen Kedi Electronics Co., Ltd.',
    material: 'ABS + PC Fireproof, Magnetic Coil',
    colorVariant: 'Matte Black / Space Gray',
    packagingType: 'Individual Color Box + Master Carton',
    hsCode: '8507.60.0000',
    boxLengthCm: 45,
    boxWidthCm: 32,
    boxHeightCm: 28,
    pcsPerBox: 40,
    unitWeightG: 220,
    grossWeightKg: 10.5,
    netWeightKg: 8.8,
    quantity: 1000,
    quantityUnit: 'pcs',
    targetPriceUsd: 8.5,
    moq: 500,
    sampleQuantity: 2,
    quantityTolerancePercent: 5,
    annualEstimatedQuantity: 15000,
    deliveryLeadTimeDays: 25,
    price1688Rmb: 48.5,
    domesticShippingRmb: 150,
    marginPercent: 25,
    clientUnitPriceUsd: 8.41,
    totalQuotationUsd: 8410.0,
    estimatedProfitUsd: 1682.0,
    inquiryExpenses: [
      {
        id: 'exp_001_sample',
        category: 'Sample Purchase',
        title: '1688 Custom Logo Samples (2 units)',
        amount: 150,
        currency: 'RMB',
        amountUsd: 20.69,
        amountRmb: 150,
        date: '2026-08-24',
        supplierOrPayee: 'Shenzhen Kedi Electronics Co., Ltd.',
        paymentMethod: 'WeChat Pay',
        hasFapiao: true,
        notes: '2 golden sample units with UV printed logo'
      },
      {
        id: 'exp_001_courier',
        category: 'Sample Express / Courier',
        title: 'SF Express Overnight to Client QA',
        amount: 65,
        currency: 'RMB',
        amountUsd: 8.97,
        amountRmb: 65,
        date: '2026-08-25',
        supplierOrPayee: 'SF Express (顺丰速运)',
        paymentMethod: 'Alipay',
        hasFapiao: true,
        notes: 'Air Express tracking #SF1083921890'
      },
      {
        id: 'exp_001_qc',
        category: 'QC & Inspection',
        title: 'Pre-shipment Battery Capacity Test',
        amount: 500,
        currency: 'RMB',
        amountUsd: 68.97,
        amountRmb: 500,
        date: '2026-08-26',
        supplierOrPayee: 'Shenzhen TechQC Lab',
        paymentMethod: 'Bank Transfer',
        hasFapiao: true,
        notes: 'CE/FCC and battery drop tests'
      }
    ],
    totalExpensesUsd: 98.63,
    totalExpensesRmb: 715.0,
    netProfitAfterExpensesUsd: 1583.37,
    orderStatus: 'Quoted to Client',
    notes: 'Client requested matte black finish, custom UV logo print, CE/FCC certificates included.',
    updatedAt: '2026-08-25T14:30:00.000Z',
  },
  {
    id: 'inq_sample_002',
    inquiryNumber: 'INQ-2026-002',
    date: '2026-08-22',
    customerName: 'Nordic Lifestyle ApS',
    customerContact: 'soren@nordiclifestyle.dk (WhatsApp: +45 20 12 34 56)',
    country: 'Denmark',
    product: 'Ceramic Pour-Over Coffee Dripper & Glass Server Set',
    productUrl1688: 'https://detail.1688.com/offer/68901245.html',
    supplierName: 'Chaozhou Jinghua Porcelain Factory',
    material: 'High Borosilicate Glass, Matte Ceramic, Walnut Base',
    colorVariant: 'Matte White Ceramic / Clear Glass',
    packagingType: 'Custom Gift Box + EVA Foam Insert',
    hsCode: '6912.00.1000',
    boxLengthCm: 52,
    boxWidthCm: 38,
    boxHeightCm: 44,
    pcsPerBox: 12,
    unitWeightG: 750,
    grossWeightKg: 11.2,
    netWeightKg: 9.0,
    quantity: 500,
    quantityUnit: 'sets',
    targetPriceUsd: 6.0,
    moq: 300,
    sampleQuantity: 1,
    quantityTolerancePercent: 3,
    annualEstimatedQuantity: 5000,
    deliveryLeadTimeDays: 30,
    price1688Rmb: 32.0,
    domesticShippingRmb: 80,
    marginPercent: 30,
    clientUnitPriceUsd: 5.76,
    totalQuotationUsd: 2880.0,
    estimatedProfitUsd: 664.0,
    inquiryExpenses: [
      {
        id: 'exp_002_sample',
        category: 'Sample Purchase',
        title: 'Chaozhou Ceramic Sample Set',
        amount: 85,
        currency: 'RMB',
        amountUsd: 11.72,
        amountRmb: 85,
        date: '2026-08-22',
        supplierOrPayee: 'Chaozhou Jinghua Porcelain Factory',
        paymentMethod: 'WeChat Pay',
        hasFapiao: true,
      },
      {
        id: 'exp_002_courier',
        category: 'Sample Express / Courier',
        title: 'SF Express Fragile Glass Courier to Office',
        amount: 42,
        currency: 'RMB',
        amountUsd: 5.79,
        amountRmb: 42,
        date: '2026-08-23',
        supplierOrPayee: 'SF Express (顺丰速运)',
        paymentMethod: 'Alipay',
        hasFapiao: true,
      }
    ],
    totalExpensesUsd: 17.51,
    totalExpensesRmb: 127.0,
    netProfitAfterExpensesUsd: 646.49,
    orderStatus: 'Sample Approved',
    notes: 'Sample approved by client. Master cartons require double-fluted 5-ply corrugated cardboard.',
    updatedAt: '2026-08-25T09:15:00.000Z',
  },
  {
    id: 'inq_sample_003',
    inquiryNumber: 'INQ-2026-003',
    date: '2026-08-20',
    customerName: 'Casa Bella Furnishings',
    customerContact: 'info@casabella.mx',
    country: 'Mexico',
    product: 'Velvet Ergonomic Office Chair with Gold Base',
    productUrl1688: 'https://detail.1688.com/offer/81239044.html',
    supplierName: 'Anji Mingfa Furniture Co., Ltd.',
    material: 'Dutch Velvet Fabric, High Density Foam, Chrome Plated Steel',
    colorVariant: 'Emerald Green / Rose Gold Base',
    packagingType: 'Brown Mailer Box (E-Commerce Ready)',
    hsCode: '9401.30.0000',
    boxLengthCm: 68,
    boxWidthCm: 62,
    boxHeightCm: 38,
    pcsPerBox: 1,
    unitWeightG: 11500,
    grossWeightKg: 13.5,
    netWeightKg: 11.5,
    quantity: 120,
    quantityUnit: 'units',
    targetPriceUsd: 35.0,
    moq: 50,
    sampleQuantity: 1,
    quantityTolerancePercent: 0,
    annualEstimatedQuantity: 1200,
    deliveryLeadTimeDays: 20,
    price1688Rmb: 195.0,
    domesticShippingRmb: 600,
    marginPercent: 20,
    clientUnitPriceUsd: 33.1,
    totalQuotationUsd: 3972.0,
    estimatedProfitUsd: 662.0,
    inquiryExpenses: [
      {
        id: 'exp_003_travel',
        category: 'Factory Travel & Transit',
        title: 'High-Speed Rail Gaotie Roundtrip (Hangzhou <-> Anji)',
        amount: 190,
        currency: 'RMB',
        amountUsd: 26.21,
        amountRmb: 190,
        date: '2026-08-21',
        supplierOrPayee: 'China Railway (12306)',
        paymentMethod: 'Alipay',
        hasFapiao: true,
        notes: 'On-site factory visit to check velvet fabric lot'
      },
      {
        id: 'exp_003_didi',
        category: 'Factory Travel & Transit',
        title: 'Didi Taxi Anji Station to Industrial Park Factory',
        amount: 85,
        currency: 'RMB',
        amountUsd: 11.72,
        amountRmb: 85,
        date: '2026-08-21',
        supplierOrPayee: 'Didi Chuxing (滴滴出行)',
        paymentMethod: 'WeChat Pay',
        hasFapiao: true,
      }
    ],
    totalExpensesUsd: 37.93,
    totalExpensesRmb: 275.0,
    netProfitAfterExpensesUsd: 624.07,
    orderStatus: 'In Production',
    notes: 'Deposit paid 30%. Expected factory completion by Sept 10. Container booking pending.',
    updatedAt: '2026-08-26T00:10:00.000Z',
  },
  {
    id: 'inq_sample_004',
    inquiryNumber: 'INQ-2026-004',
    date: '2026-08-25',
    customerName: 'Oz Fitness Co.',
    customerContact: '+61 412 345 678',
    country: 'Australia',
    product: 'Heavy Duty Fabric Resistance Bands Set (5-Pack with Mesh Bag)',
    productUrl1688: 'https://detail.1688.com/offer/59231802.html',
    supplierName: 'Yiwu Topfit Sporting Goods',
    material: 'Polyester Cotton + Latex Wire Threading',
    colorVariant: 'Pink, Purple, Cyan, Charcoal Gradient',
    packagingType: 'OPP Bag + Breathable Nylon Mesh Bag',
    hsCode: '9506.91.0000',
    boxLengthCm: 48,
    boxWidthCm: 36,
    boxHeightCm: 30,
    pcsPerBox: 50,
    unitWeightG: 380,
    grossWeightKg: 20.5,
    netWeightKg: 19.0,
    quantity: 2000,
    quantityUnit: 'sets',
    targetPriceUsd: 2.5,
    moq: 1000,
    sampleQuantity: 3,
    quantityTolerancePercent: 5,
    annualEstimatedQuantity: 30000,
    deliveryLeadTimeDays: 15,
    price1688Rmb: 14.2,
    domesticShippingRmb: 120,
    marginPercent: 22,
    clientUnitPriceUsd: 2.39,
    totalQuotationUsd: 4780.0,
    estimatedProfitUsd: 860.0,
    orderStatus: '1688 Sourcing',
    notes: 'Comparing 3 factory quotations for elastic durability. Requested pantone color match.',
    updatedAt: '2026-08-26T01:00:00.000Z',
  },
];
