import { ExpenseItem } from '../types';

export const SAMPLE_EXPENSES: ExpenseItem[] = [
  {
    id: 'exp-001',
    expenseNumber: 'EXP-2026-001',
    date: '2026-03-12',
    category: 'Transport',
    subType: 'Gaotie / High-Speed Train',
    title: 'High-Speed Train (Gaotie): Guangzhou South to Yiwu',
    amount: 685,
    currency: 'RMB',
    amountRmb: 685,
    amountUsd: 94.48,
    city: 'Yiwu',
    destinationRoute: 'Guangzhou South -> Yiwu Railway Station',
    factoryOrPartner: 'Yiwu International Trade City / Market Dist 2',
    factoryOrSupplier: 'Yiwu International Trade City / Market Dist 2',
    hasFapiao: true,
    paymentMethod: 'WeChat Pay',
    notes: 'First-class Gaotie seat for overnight market procurement run',
    createdAt: '2026-03-12T08:30:00.000Z',
    updatedAt: '2026-03-12T08:30:00.000Z',
  },
  {
    id: 'exp-002',
    expenseNumber: 'EXP-2026-002',
    date: '2026-03-12',
    category: 'Hotel & Accommodation',
    subType: 'Business Hotel',
    title: 'Yiwu Marriott Hotel - 2 Nights (Market Audit)',
    amount: 960,
    currency: 'RMB',
    amountRmb: 960,
    amountUsd: 132.41,
    city: 'Yiwu',
    destinationRoute: 'Chouzhou North Road, Yiwu',
    factoryOrPartner: 'Yiwu Market Suppliers',
    factoryOrSupplier: 'Yiwu Market Suppliers',
    hasFapiao: true,
    paymentMethod: 'Alipay',
    notes: '2 nights stay for Yiwu jewelry and electronics sourcing',
    createdAt: '2026-03-12T18:00:00.000Z',
    updatedAt: '2026-03-12T18:00:00.000Z',
  },
  {
    id: 'exp-003',
    expenseNumber: 'EXP-2026-003',
    date: '2026-03-13',
    category: 'Food & Meals',
    subType: 'Factory Lunch & Dinner',
    title: 'Business Lunch with Mold Factory Boss & Engineers',
    amount: 320,
    currency: 'RMB',
    amountRmb: 320,
    amountUsd: 44.14,
    city: 'Dongguan',
    destinationRoute: 'Chang’an Town Industrial Park',
    factoryOrPartner: 'Dongguan Precision Plastic Mold Co.',
    factoryOrSupplier: 'Dongguan Precision Plastic Mold Co.',
    hasFapiao: true,
    paymentMethod: 'WeChat Pay',
    notes: 'Discussed tooling timeline and sample tolerances over lunch',
    createdAt: '2026-03-13T13:15:00.000Z',
    updatedAt: '2026-03-13T13:15:00.000Z',
  },
  {
    id: 'exp-004',
    expenseNumber: 'EXP-2026-004',
    date: '2026-03-14',
    category: 'Transport',
    subType: 'Didi / Factory Van',
    title: 'Didi Premier: Shenzhen North to Dongguan Tangxia Factory Zone',
    amount: 215,
    currency: 'RMB',
    amountRmb: 215,
    amountUsd: 29.66,
    city: 'Dongguan',
    destinationRoute: 'Shenzhen North -> Dongguan Tangxia',
    factoryOrPartner: 'Dongguan Great Power Battery Factory',
    factoryOrSupplier: 'Dongguan Great Power Battery Factory',
    hasFapiao: true,
    paymentMethod: 'WeChat Pay',
    notes: 'Expressway tolls (¥35) included in Didi invoice',
    createdAt: '2026-03-14T09:40:00.000Z',
    updatedAt: '2026-03-14T09:40:00.000Z',
  },
  {
    id: 'exp-005',
    expenseNumber: 'EXP-2026-005',
    date: '2026-03-15',
    category: 'Factory Escort & Driver',
    subType: 'Private Driver Day Hire',
    title: 'Full-day Driver & Car: Foshan Furniture & Ceramic Factories',
    amount: 550,
    currency: 'RMB',
    amountRmb: 550,
    amountUsd: 75.86,
    city: 'Foshan',
    destinationRoute: 'Shunde Lecong -> Nanhai District (4 factories)',
    factoryOrPartner: 'Shunde Oppein Furniture & Foshan Tile Hub',
    factoryOrSupplier: 'Shunde Oppein Furniture & Foshan Tile Hub',
    hasFapiao: false,
    paymentMethod: 'Alipay',
    notes: 'Driver escorted to 4 distant factory compounds throughout Shunde',
    createdAt: '2026-03-15T17:30:00.000Z',
    updatedAt: '2026-03-15T17:30:00.000Z',
  },
  {
    id: 'exp-006',
    expenseNumber: 'EXP-2026-006',
    date: '2026-03-16',
    category: 'Hotel & Accommodation',
    subType: 'Industrial Park Hotel',
    title: 'Shenzhen Bao’an Airport Hotel (Early Factory Departure)',
    amount: 420,
    currency: 'RMB',
    amountRmb: 420,
    amountUsd: 57.93,
    city: 'Shenzhen',
    destinationRoute: 'Bao’an Fuyong, Shenzhen',
    factoryOrPartner: 'Shenzhen Topband Electronics',
    factoryOrSupplier: 'Shenzhen Topband Electronics',
    hasFapiao: true,
    paymentMethod: 'Credit Card',
    notes: 'Convenient base for Bao’an hardware suppliers and morning high-speed train',
    createdAt: '2026-03-16T21:00:00.000Z',
    updatedAt: '2026-03-16T21:00:00.000Z',
  },
  {
    id: 'exp-007',
    expenseNumber: 'EXP-2026-007',
    date: '2026-03-17',
    category: 'SIM, VPN & Supplies',
    subType: 'Data & PPE',
    title: 'China Unicom Unlimited 5G Data Pack & Factory Safety Shoes',
    amount: 198,
    currency: 'RMB',
    amountRmb: 198,
    amountUsd: 27.31,
    city: 'Guangzhou',
    destinationRoute: 'Tianhe, Guangzhou',
    factoryOrPartner: 'Local Telecom & Safety Gear Hub',
    factoryOrSupplier: 'Local Telecom & Safety Gear Hub',
    hasFapiao: true,
    paymentMethod: 'WeChat Pay',
    notes: 'Required for remote video streaming inspections inside metal casting plant',
    createdAt: '2026-03-17T11:00:00.000Z',
    updatedAt: '2026-03-17T11:00:00.000Z',
  },
];
