import { ServiceRequest } from '../types';

export const SAMPLE_SERVICES: ServiceRequest[] = [
  {
    id: 'srv_1',
    serviceNumber: 'SRV-2026-001',
    date: '2026-03-12',
    clientName: 'Ahmad Al-Mansoor',
    clientContact: '+966 50 123 4567',
    wechatId: 'ahmad_mansoor_sa',
    country: 'Saudi Arabia',
    category: 'Medical & Clinic Assistance',
    title: 'Find Top Orthopedic Knee Specialist Clinic for Uncle in Guangzhou',
    description: 'Client needs appointment and treatment plan for his 68-year-old uncle suffering from severe osteoarthritic knee pain. Requires: 1) English-speaking medical interpreter for 2 hospital visits; 2) VIP booking at Nanfang Hospital or Guangdong Provincial People Hospital Orthopedic Clinic; 3) Assistance with medical record translation and pharmacy prescription pickup.',
    cityLocation: 'Guangzhou',
    status: 'In Progress',
    priority: 'High',
    quoteCurrency: 'USD',
    clientFee: 1200,
    estimatedCost: 450,
    estimatedProfitUsd: 750,
    estimatedProfitRmb: 5437.5,
    paymentStatus: 'Deposit Received',
    assignedPartner: 'Dr. Lin Medical Concierge (Guangzhou)',
    partnerContact: '+86 138 0020 8899 / wechat: gz_medilink',
    partnerCommission: 300,
    targetDate: '2026-03-24',
    notes: 'Patient MRI scans already sent via WeChat. Confirmed appointment with Chief Physician Prof. Zhang on Thursday morning. Airport wheelchair assistance also requested.',
    createdAt: '2026-03-12T09:00:00.000Z',
    updatedAt: '2026-03-14T11:30:00.000Z',
  },
  {
    id: 'srv_2',
    serviceNumber: 'SRV-2026-002',
    date: '2026-03-10',
    clientName: 'Marcus Vance',
    clientContact: '+1 415 889 2314',
    wechatId: 'marcus_vance_sf',
    country: 'United States',
    category: 'Company Registration',
    title: 'Register WFOE Trading Company & Corporate Bank Account in Shenzhen',
    description: 'Assisting Marcus with registering a Wholly Foreign-Owned Enterprise (WFOE) in Shenzhen Qianhai Free Trade Zone for consumer electronics export. Deliverables: 1) Company name pre-approval; 2) Business license (营业执照) issuance; 3) Official company chops (公章、财务章、法人章); 4) Assistance opening corporate multi-currency RMB/USD account at Bank of China.',
    cityLocation: 'Shenzhen',
    status: 'In Progress',
    priority: 'Urgent',
    quoteCurrency: 'USD',
    clientFee: 2800,
    estimatedCost: 1100,
    estimatedProfitUsd: 1700,
    estimatedProfitRmb: 12325,
    paymentStatus: 'Deposit Received',
    assignedPartner: 'Shenzhen Yida Enterprise Solutions (Mr. Chen)',
    partnerContact: '+86 139 2345 6789 / wechat: yida_corp_sz',
    partnerCommission: 800,
    targetDate: '2026-04-15',
    notes: 'Articles of association notarized at Chinese consulate in San Francisco. Awaiting apostille certificate delivery to Shenzhen office next week.',
    createdAt: '2026-03-10T14:20:00.000Z',
    updatedAt: '2026-03-15T16:00:00.000Z',
  },
  {
    id: 'srv_3',
    serviceNumber: 'SRV-2026-003',
    date: '2026-03-05',
    clientName: 'Carlos Mendez',
    clientContact: '+52 55 4123 7890',
    wechatId: 'carlos_mendez_mx',
    country: 'Mexico',
    category: 'Translation & Business Escort',
    title: 'Professional Spanish/English/Mandarin Guide for 4-Day Yiwu Market Visit',
    description: 'Full-time commercial translator and business escort for client visiting Yiwu International Trade City District 1-4 for kitchenware and plastic housewares. Includes booth price negotiation, collecting sample business cards, catalog photo compilation, and daily expense reports.',
    cityLocation: 'Yiwu',
    status: 'Completed',
    priority: 'Medium',
    quoteCurrency: 'USD',
    clientFee: 850,
    estimatedCost: 400,
    estimatedProfitUsd: 450,
    estimatedProfitRmb: 3262.5,
    paymentStatus: 'Fully Paid',
    assignedPartner: 'Sophie Wu (Yiwu Freelance Interpreter)',
    partnerContact: '+86 186 5798 1122 / wechat: sophie_yiwu',
    partnerCommission: 350,
    targetDate: '2026-03-09',
    notes: 'Client was extremely satisfied with the supplier leads collected. Placed 2 sample orders directly on site.',
    createdAt: '2026-03-05T08:15:00.000Z',
    updatedAt: '2026-03-09T18:00:00.000Z',
  },
  {
    id: 'srv_4',
    serviceNumber: 'SRV-2026-004',
    date: '2026-03-14',
    clientName: 'Elena Rostova',
    clientContact: '+44 7700 900345',
    wechatId: 'elena_rostova_uk',
    country: 'United Kingdom',
    category: 'Factory Audit & Verification',
    title: 'On-Site Factory Legitimacy & Quality Audit in Ningbo (Lighting Manufacturer)',
    description: 'Thorough on-site verification of Ningbo Huaguang Lighting Co. before client wires a $45,000 deposit. Scope: 1) Verify factory physical existence, production lines, and worker headcounts; 2) Check authentic ISO 9001 and CE test certificates; 3) Conduct live video walkthrough with client in London.',
    cityLocation: 'Ningbo',
    status: 'New Request',
    priority: 'High',
    quoteCurrency: 'USD',
    clientFee: 600,
    estimatedCost: 220,
    estimatedProfitUsd: 380,
    estimatedProfitRmb: 2755,
    paymentStatus: 'Unpaid',
    assignedPartner: 'Zhejiang SinoVerify QC Team',
    partnerContact: '+86 158 6889 7733',
    partnerCommission: 180,
    targetDate: '2026-03-20',
    notes: 'Quotation sent to Elena on WhatsApp. Waiting for signed agreement and payment to dispatch the inspector.',
    createdAt: '2026-03-14T10:00:00.000Z',
    updatedAt: '2026-03-14T10:00:00.000Z',
  },
];
